variable "region" {}
variable "zone" {}
variable "network_name" {}
variable "subnetwork_id" {}
variable "internal_ip_name" {}
variable "internal_ip_address" {}
variable "external_ip_name" {}
variable "instance_name" {}
variable "machine_type" {}
variable "ssh_keys" {}
variable "image" {}
